### ISSUE TITLE
how exclude the animation?

### ISSUE THREAD

**Issue by txxxtxx** [RowlandOti/CartCounter#3]
hi, how exclude the animation?

**Comment by txxxtxx** [comment]
i find the code  ' cc_is_animate_layout'

**Comment by RowlandOti** [comment]
Hi, @txxxtxx  sorry for the very late response. I have just updated the code to the latest version. Kindly use:

>compile 'com.rowland.cartcounter:CartCounter:1.0.0-alpha-1'

This will fully provide the capability to disable the animation (See example in README.md). I hope this will help others too.
